apiVersion: apps/v1
kind: Deployment
metadata: 
  name: db
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: postgres:15.0
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_DB 
            value: "kubenews"
          - name: POSTGRES_USER
            value: "kubenews"
          - name: POSTGRES_PASSWORD
            value: "Pg#123"
---
apiVersion: v1
kind: Service
metadata:
  name: svcdb
spec:
  selector:
    app: db
  ports:
  - port: 5432
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: webapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
      annotations:
        prometheus.io/scrape: "true"  
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: webapp
        image: mbouzon/kube-news:latest
        ports:
          - containerPort: 8080
        env:
          - name: DB_DATABASE 
            value: "kubenews"
          - name: DB_USERNAME
            value: "kubenews"
          - name: DB_PASSWORD
            value: "Pg#123"
          - name: DB_HOST
            value: "svcdb"
---

apiVersion: v1
kind: Service
metadata:
  name: svcwebapp
spec:
  selector:
    app: webapp
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer