apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: meurs
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: convtemp
        image: fabricioveronez/web-page:blue
        ports:
          - containerPort: 80